"""
SQLAlchemy database models for the Anti-Cheat Detection System.
"""

from datetime import datetime
from typing import Optional, List
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean, Text, 
    ForeignKey, Index, UniqueConstraint, LargeBinary, JSON
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, Session
from sqlalchemy.sql import func

Base = declarative_base()


class Student(Base):
    """Student information and face embeddings."""
    __tablename__ = "students"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    roll_number = Column(String(50), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=False)
    class_id = Column(String(50), nullable=False, index=True)
    email = Column(String(200), nullable=True)
    face_embedding = Column(LargeBinary, nullable=True)  # Serialized numpy array
    embedding_version = Column(String(20), default="facenet_v1")
    
    # Metadata
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
    is_active = Column(Boolean, default=True)
    
    # Relationships
    tracking_sessions = relationship("TrackingSession", back_populates="student")
    behavior_events = relationship("BehaviorEvent", back_populates="student")
    alerts = relationship("Alert", back_populates="student")
    
    __table_args__ = (
        Index('idx_student_class_roll', 'class_id', 'roll_number'),
    )


class TrackingSession(Base):
    """Tracking session for monitoring periods."""
    __tablename__ = "tracking_sessions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(100), unique=True, nullable=False, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    camera_id = Column(String(50), nullable=False)
    
    # Session timing
    start_time = Column(DateTime, nullable=False, default=func.now())
    end_time = Column(DateTime, nullable=True)
    duration_seconds = Column(Integer, nullable=True)
    
    # Tracking statistics
    total_frames = Column(Integer, default=0)
    tracked_frames = Column(Integer, default=0)
    recognition_count = Column(Integer, default=0)
    track_losses = Column(Integer, default=0)
    
    # Final scores
    final_suspicion_score = Column(Float, default=0.0)
    max_suspicion_score = Column(Float, default=0.0)
    alert_count = Column(Integer, default=0)
    
    # Metadata
    created_at = Column(DateTime, default=func.now())
    
    # Relationships
    student = relationship("Student", back_populates="tracking_sessions")
    behavior_events = relationship("BehaviorEvent", back_populates="session")
    alerts = relationship("Alert", back_populates="session")
    
    __table_args__ = (
        Index('idx_session_student_time', 'student_id', 'start_time'),
        Index('idx_session_camera_time', 'camera_id', 'start_time'),
    )


class BehaviorEvent(Base):
    """Individual suspicious behavior events."""
    __tablename__ = "behavior_events"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    event_id = Column(String(100), unique=True, nullable=False, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    session_id = Column(Integer, ForeignKey("tracking_sessions.id"), nullable=False)
    
    # Event details
    event_type = Column(String(50), nullable=False, index=True)
    confidence = Column(Float, nullable=False)
    duration_seconds = Column(Float, nullable=False)
    timestamp = Column(DateTime, nullable=False, default=func.now())
    
    # Evidence
    evidence_path = Column(String(500), nullable=True)
    bbox_x1 = Column(Float, nullable=True)
    bbox_y1 = Column(Float, nullable=True)
    bbox_x2 = Column(Float, nullable=True)
    bbox_y2 = Column(Float, nullable=True)
    
    # Additional metadata
    event_metadata = Column(JSON, nullable=True)
    frame_number = Column(Integer, nullable=True)
    camera_id = Column(String(50), nullable=False)
    
    # Relationships
    student = relationship("Student", back_populates="behavior_events")
    session = relationship("TrackingSession", back_populates="behavior_events")
    
    __table_args__ = (
        Index('idx_behavior_student_type_time', 'student_id', 'event_type', 'timestamp'),
        Index('idx_behavior_session_time', 'session_id', 'timestamp'),
    )


class Alert(Base):
    """Alert notifications generated by the system."""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_id = Column(String(100), unique=True, nullable=False, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    session_id = Column(Integer, ForeignKey("tracking_sessions.id"), nullable=False)
    
    # Alert details
    alert_level = Column(String(20), nullable=False, index=True)  # warning, critical
    alert_type = Column(String(50), nullable=False)
    composite_score = Column(Float, nullable=False)
    contributing_behaviors = Column(JSON, nullable=False)  # List of behavior types
    
    # Evidence
    evidence_screenshot = Column(String(500), nullable=False)
    annotated_screenshot = Column(String(500), nullable=True)
    
    # Timing
    timestamp = Column(DateTime, nullable=False, default=func.now())
    resolved_at = Column(DateTime, nullable=True)
    
    # Email notification
    email_sent = Column(Boolean, default=False)
    email_sent_at = Column(DateTime, nullable=True)
    email_recipients = Column(JSON, nullable=True)  # List of email addresses
    email_retry_count = Column(Integer, default=0)
    
    # Metadata
    camera_id = Column(String(50), nullable=False)
    thresholds_at_time = Column(JSON, nullable=True)  # Thresholds in effect
    
    # Relationships
    student = relationship("Student", back_populates="alerts")
    session = relationship("TrackingSession", back_populates="alerts")
    
    __table_args__ = (
        Index('idx_alert_student_level_time', 'student_id', 'alert_level', 'timestamp'),
        Index('idx_alert_level_time', 'alert_level', 'timestamp'),
        Index('idx_alert_email_status', 'email_sent', 'timestamp'),
    )


class EmailLog(Base):
    """Email notification log."""
    __tablename__ = "email_logs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=False)
    
    # Email details
    recipient = Column(String(200), nullable=False)
    subject = Column(String(500), nullable=False)
    sent_at = Column(DateTime, nullable=False, default=func.now())
    success = Column(Boolean, nullable=False)
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0)
    
    # SMTP details
    smtp_server = Column(String(200), nullable=True)
    smtp_response = Column(Text, nullable=True)
    
    __table_args__ = (
        Index('idx_email_log_alert_time', 'alert_id', 'sent_at'),
        Index('idx_email_log_success_time', 'success', 'sent_at'),
    )


class SystemMetrics(Base):
    """System performance and health metrics."""
    __tablename__ = "system_metrics"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=func.now(), index=True)
    
    # Performance metrics
    cpu_usage = Column(Float, nullable=False)
    memory_usage = Column(Float, nullable=False)
    gpu_usage = Column(Float, nullable=True)
    fps = Column(Float, nullable=False)
    processing_latency = Column(Float, nullable=False)
    
    # System state
    active_tracks = Column(Integer, nullable=False)
    active_students = Column(Integer, nullable=False)
    alerts_generated = Column(Integer, nullable=False)
    
    # Camera status
    camera_status = Column(JSON, nullable=True)  # Dict of camera_id -> status
    
    __table_args__ = (
        Index('idx_metrics_timestamp', 'timestamp'),
    )


class Configuration(Base):
    """System configuration history."""
    __tablename__ = "configurations"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    config_key = Column(String(100), nullable=False, index=True)
    config_value = Column(JSON, nullable=False)
    
    # Metadata
    created_at = Column(DateTime, nullable=False, default=func.now())
    created_by = Column(String(100), nullable=False)
    is_active = Column(Boolean, default=True)
    
    __table_args__ = (
        Index('idx_config_key_active', 'config_key', 'is_active'),
    )


class AuditLog(Base):
    """Audit trail for system actions."""
    __tablename__ = "audit_logs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, default=func.now(), index=True)
    
    # Action details
    action = Column(String(100), nullable=False, index=True)
    entity_type = Column(String(50), nullable=False)
    entity_id = Column(String(100), nullable=True)
    
    # User context
    user_id = Column(String(100), nullable=True)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(String(500), nullable=True)
    
    # Change details
    old_values = Column(JSON, nullable=True)
    new_values = Column(JSON, nullable=True)
    
    # Additional context
    audit_metadata = Column(JSON, nullable=True)
    
    __table_args__ = (
        Index('idx_audit_action_time', 'action', 'timestamp'),
        Index('idx_audit_entity_time', 'entity_type', 'timestamp'),
    )


# Database utility functions
def create_tables(engine):
    """Create all database tables."""
    Base.metadata.create_all(engine)


def drop_tables(engine):
    """Drop all database tables."""
    Base.metadata.drop_all(engine)


def get_table_names():
    """Get list of all table names."""
    return [table.name for table in Base.metadata.tables.values()]